- name: Playbook to install Ansible Molecule in WSL2
  hosts: localhost
  # connection: local
  become: true
  gather_facts: true
  ignore_errors: true
  vars:
    molecule_driver: docker
  tasks:

    - name: Include dpkg_vars
      ansible.builtin.include_vars: vars/main.yml

## WSL prep
# https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/
    - name: Enable systemd for WSL2
      ansible.builtin.lineinfile:
        path: /etc/wsl.conf
        insertbefore: BOF
        line: "{{ item }}"
        create: true
        mode: '0644'
      with_items:
        - '[boot]'
        - 'systemd=true'
      when: enable_wsl_systemd


## Docker-in-WSL2 prep
    - name: Docker clean-up
      when: docker_cleanup
      block:
        - name: "Delete docker.list"
          ansible.builtin.file:
            path: /etc/apt/sources.list.d/docker.list
            state: absent
        - name: "Delete docker.gpg"
          ansible.builtin.file:
            path: /etc/apt/keyrings/docker.gpg
            state: absent

    - name: "Docker pre-reqs"
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
      register: docker_pre_reqs_installed

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: "{{ apt_docker_keyring_location }}"
      when: docker_pre_reqs_installed
      register: docker_gpg_key_installed

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb [arch={{ dpkg_arch }} signed-by={{ apt_docker_keyring_location }}] {{ docker_base_url }} {{ ansible_distribution_release }} stable
        filename: docker
        state: present
      register: docker_repo_installed
      when: docker_gpg_key_installed

# ## Docker-in-WSL2 installation

    - name: "APT: Install PIP"
      ansible.builtin.apt:
        name:
          - python3-pip
          - libssl-dev
        state: present
        update_cache: true


    - name: Install docker
      when: install_docker
      block:
        - name: Update apt and install docker-ce
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-compose-plugin
            state: present
            update_cache: true
          register: docker_installed
          when: docker_repo_installed

        - name: Install Docker Module for Python
          ansible.builtin.pip:
            name: docker
          when: docker_installed

        - name: Ensure group "docker" exists
          ansible.builtin.group:
            name: docker
            state: present

        - name: Added user to docker group
          ansible.builtin.user:
            name: luis
            groups: docker
            append: true

        - name: Group change notification
          ansible.builtin.debug:
            msg: "You now need to manually run: newgrp docker"

### Molecule installation
## From:
# https://ansible.readthedocs.io/projects/molecule/installation/#requirements

    - name: "PIP: Install Molecule"
      become: false
      ansible.builtin.pip:
        name: molecule
        executable: pip3
        # extra_args: "--user"
        state: present

    # - name: "PIP: Install/upgrade setuptools"
    #   become: false
    #   ansible.builtin.pip:
    #     name: setuptools
    #     executable: pip3
    #     extra_args: "--upgrade --user"
    #     state: present

    # - name: "PIP: Install/upgrade ansible-lint"
    #   become: false
    #   ansible.builtin.pip:
    #     name: ansible-lint
    #     executable: pip3
    #     extra_args: "--user"
    #     state: present

    # - name: "PIP: Install Molecule Docker"
    #   become: false
    #   ansible.builtin.pip:
    #     name: molecule-docker
    #     executable: pip3
    #     extra_args: "--user"
    #     state: present

    # - name: "PIP: Install Molecule Docker Driver"
    #   become: false
    #   ansible.builtin.pip:
    #     name: molecule-plugins[{{ molecule_driver }}]
    #     executable: pip3
    #     extra_args: "--user"
    #     state: present
    #   register: molecule_driver_result

    # - name: Debug Docker Driver install
    #   ansible.builtin.debug:
    #     var: molecule_driver_result
