---
# vars file for installer

## vars to build docker repo URI

dpkg_arch: >-
    {%- if ansible_distribution_file_variety == 'Debian' and ansible_architecture == 'aarch64' -%}
        arm64
    {%- elif ansible_distribution_file_variety == 'Debian' and ansible_architecture == 'x86_64' -%}
        amd64
    {%- elif ansible_distribution == 'Darwin' -%}
        darwin-amd64
    {%- elif ansible_distribution == 'Windows' -%}
        amd64
    {% endif %}


### vars to control playbook components

## Main features
# Install docker
install_docker_required: true

# Install Ansible
install_ansible_required: false

# Install Molecule
install_molecule_required: true

############
# Set as one of:
# azure
# containers
# docker
# ec2
# gce
# podman
# vagrant
#
# Reference: https://github.com/ansible-community/molecule-plugins
molecule_driver: docker

molecule_driver_cleanup: true

# Enable config changes to enable systemd in your WSL instance
enable_wsl_systemd: false

# Cleanup existing apt lists and keys
docker_cleanup_required: true

# Location to save docker keyring using apt
apt_docker_keyring_location: /etc/apt/keyrings/docker.gpg

# Base URL for Docker repository
docker_base_url: https://download.docker.com/linux/ubuntu
