---

## WSL prep
# https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/
    - name: Enable systemd for WSL2
      ansible.builtin.lineinfile:
        path: /etc/wsl.conf
        insertbefore: BOF
        line: "{{ item }}"
        create: true
        mode: '0644'
      with_items:
        - '[boot]'
        - 'systemd=true'
      when: enable_wsl_systemd
