---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2204
    image: ubuntu:22.04
    dockerfile: ../common/Dockerfile_ubuntu2204
    entrypoint: "/usr/bin/bash"
    pre_build_image: false

  - name: ubuntu2004
    image: ubuntu:20.04
    dockerfile: ../common/Dockerfile_ubuntu2004
    entrypoint: "/usr/bin/bash"
    pre_build_image: false

provisioner:
  name: ansible
verifier:
  name: ansible
