# .github/workflows/ansible-lint.yml

name: ansible-lint
on:
  pull_request:
    branches: ["main", "stable", "release/v*"]
  push:
    branches: ["main", "stable", "release/v*"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
  hadolint:
      name: Hadolint
      runs-on: ubuntu-latest
      container: hadolint/hadolint:latest-debian
      steps:
        - uses: actions/checkout@v3
        - uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: "molecule/common/Dockerfile_*"
            recursive: true
